version: 1
disable_existing_loggers: False
formatters:
  generic:
    format: "%(asctime)s %(levelname)-8s: %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  colored:
    (): colorlog.ColoredFormatter
    format: "%(asctime)s %(log_color)s%(levelname)-8s: %(light_black)s%(name)s%(reset)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG: black
      INFO: green
      WARNING: light_red
      ERROR: red
      CRITICAL: white, bg_red
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout

loggers:
  root:
    level: INFO
    handlers: [console]
    propagate: 0
  rxconfig:
    level: DEBUG
    handlers: [console]
    propagate: 0
  app:
    level: DEBUG
    handlers: [console]
    propagate: 0
  appkit_assistant:
    level: DEBUG
    handlers: [console]
    propagate: 0
  appkit_imagecreator:
    level: DEBUG
    handlers: [console]
    propagate: 0
  appkit_commons:
    level: INFO
    handlers: [console]
    propagate: 0
  appkit_ui:
    level: INFO
    handlers: [console]
    propagate: 0
  server:
    level: DEBUG
    handlers: [console]
    propagate: 0
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: 0
  azure.core.pipeline.policies.http_logging_policy:
    level: WARNING
    handlers: [console]
    propagate: 0
  httpx:
    level: DEBUG
    handlers: [console]
    propagate: 0
  watchfiles:
    level: WARNING
    handlers: [console]
    propagate: 0
  alembic.autogenerate.compare:
    level: WARNING
    handlers: [console]
    propagate: 0
  alembic.ddl.postgresql:
    level: WARNING
    handlers: [console]
    propagate: 0
